Homework
123Boryana/JavaTraining pull request #1
Opened 2023-07-05 09:30 UTC by 123Boryana

2023-07-06 08:17 UTC, Evgeni-Georgiev requested changes
Excellent.

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkExercise1.java
> +        String[] words = {"alpha", "avatar", "trouble", "birch", "salon"};
Can add space before the variable.

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkExercise1.java
> +    public static void main(String[] args){
Space between ) and {.

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkExercise1.java
> +        for(String str : words){
Space between ) and {. And even after for. This is for better formatting of the code.

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkExercise1.java
> +            if(str.startsWith("a"))
And even after if. This is for better formatting of the code.

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkExercise2.java
> +        Scanner scanner = new Scanner(System.in);
Can add space before the variable.

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkExercise2.java
> +    public static void main(String[] args){
Space between ) and {.

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkExercise2.java
> +        for(int i = 0; i < array.length; i++){
Add spaces based on the previous remarks.

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkExercise2.java
> +
Unnecessary empty line.

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkExercise3.java
> +
Unnecessary empty line.

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkExercise3.java
> +        }
Add empty line.

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkExercise3.java
> +        }
Add empty line.

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkExercise3.java
> +        if(filteredwWords.isEmpty())
Add space after if. Good formatting. :)

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkFromMonday.java
> +        if(day >= 1 && day <= 7){
When using case, such checking is not needed. Add "default" instead. The switch will check every possible case. If none of the cases is affirmative, then the default will execute. So, remove the if statement and add default.

2023-07-06 08:17 UTC, Evgeni-Georgiev commented on src/main/java/training/day2/HomeworkFromMonday.java
> +    public static void main(String[] args) {
Add new line after the main method.

2023-07-07 07:22 UTC, Evgeni-Georgiev approved these changes
Good.

2023-07-11 05:43 UTC, intro-java approved these changes

2023-07-11 07:33 UTC, merged